name: default
kind: pipeline

pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - /tmp/cache:/cache

  install:
    image: node:12.8.0
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install --pure-lockfile

  generate:
    image: node:12.8.0
    commands:
      - yarn run generate

  deploy:
    image: lucap/drone-netlify
    site_id: 
      from_secret: netlify_site_id
    token:
      from_secret: netlify_token
    environment: production