name: default
type: docker
kind: pipeline

volumes:
  - name: cache
    host: 
      path: /tmp/cache
      
steps:
  restore-cache:
    image: drillster/drone-volume-cache
    cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH ]
    ttl: 1
    restore: true
    volumes:
      - cache:/.cache
    mount:
      - ./node_modules

  install:
    image: node:12.8.0
    commands:
      - npm install ci
      - npm config set cache /.cache -g
      - npm ci

  generate:
    image: node:12.8.0
    commands:
      - npm run generate

  deploy:
    image: lucap/drone-netlify
    site_id: 
      from_secret: netlify_site_id
    token:
      from_secret: netlify_token
    path: ./dist
    environment: [production]

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    volumes:
      - cache:/.cache
    mount:
      - ./node_modules