image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://www.perfect-derm.com
  only:
    - master
  script:
    - npm install
    - npm install netlify-cli
    - npm install core-js
    - npm run generate
    - npm netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod