image: node:8.9.0

cache:
  paths:
    - node_modules/


before_script:
  - npm install

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://www.perfect-derm.com
  only:
    - master
  script:
    - npm install netlify-cli -g
    - npm run generate
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod