[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
ID = "main"

# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "dist/"
  command = "npm run deploy"

[context.production]
  command = "BASE_URL=$URL npm run deploy"

[context.deploy-preview]
  command = "BASE_URL=$DEPLOY_PRIME_URL npm run deploy"

[context.branch-deploy]
  command = "BASE_URL=$DEPLOY_URL npm run deploy"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
  force = false
  
[[redirects]]
  from = "https://perfect-derm.com/*"
  to = "https://www.perfect-derm.com/:splat"
  status = 301
  force = true