backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "[PL] Strona główna"
        name: "homepage"
        file: "content/index/pl.json"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}
      - label: "[EN] Strona główna"
        name: "homepage"
        file: "content/index/en.json"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}
      - label: "[DE] Strona główna"
        name: "homepage"
        file: "content/index/de.json"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}