backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "Strona główna"
        name: "homepage"
        file: "content/index.json"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}
          - {label: "Baner - tytuł", name: baner_title, widget: string}
          - {label: "Baner - subtytuł", name: baner_subtitle, widget: string}
          - {label: "Baner - grafika", name: baner_image, widget: image}
          - label: "Sekcje z informacjami"
            name: "sections"
            widget: "list"
            required: false
            fields:
              - {label: "Tytuł", name: section_title, widget: string}
              - {label: "Opis", name: section_description, widget: text}
              - {label: "Obrazek", name: section_image, widget: image}
              - {label: "Przycisk - tytuł", name: section_button_title, widget: string}
              - {label: "Przycisk - link", name: section_button_link, widget: string}
              - label: "Wygląd bloku"
                name: "section_layout_block"
                widget: "select"
                options:
                  - { label: "1 kolumna", value: "single" }
                  - { label: "2 kolumny", value: "duo" }
              - label: "Umiejscowienie przycisku"
                name: "section_layout_button"
                widget: "select"
                options:
                  - { label: "Pod tekstem", value: "section_layout_button_text" }
                  - { label: "Pod grafiką", value: "section_layout_button_image" }
                  - { label: "Pod całością", value: "section_layout_button_end" }