name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm - install
      run: |
        npm ci
        npm install --silent --no-audit
    - name: npm - generate
      run: |
        npm generate
    - name: netlify 
      run: |
        netlify deploy --site=${{ NETLIFY_SITE_ID }} --auth=${{ NETLIFY_AUTH_TOKEN }} --prod --silent
        
        
      env:
        CI: true
